---
MD003:
  style: atx
MD007:
  indent: 4
MD013: false
MD024: false
MD030:
  ul_multi: 3
  ul_single: 3
MD033: false
MD035:
  style: "---"
MD044:
  code_blocks: false
  html_elements: false
  names:
    - Design System
    - JavaScript
    - TypeScript
    - Web Components
    - Padrão Digital de Governo
MD046:
  style: fenced
MD048:
  style: backtick
MD049:
  style: asterisk
MD050:
  style: asterisk
default: true
