name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
        env: 
          SSH_PRIVATE_KEY: ${{secrets.DEPLOY}}
          SOURCE: "./"
          REMOTE_HOST: "ec2-52-4-175-133.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu"
          
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-52-4-175-133.compute-1.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.DEPLOY }}
          script: |            
            cd home
            npm install
