name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY }}
          REMOTE_HOST: "ec2-52-4-175-133.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu"

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "ec2-52-4-175-133.compute-1.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.DEPLOY }}
          script: |            
            cd /home/ubuntu
            nvm use 20
            npm install
